name = "pricing-optimizer"
pages_build_output_dir = "dist"
compatibility_date = "2024-11-01"

# PWA manifest URLs:
[vars]
VITE_PWA_BASE = "/"

[env.preview]
[env.preview.vars]
VITE_PWA_BASE = "/"

[env.production]
[env.production.vars]
VITE_PWA_BASE = "/pricing-optimizer/"

[[kv_namespaces]]
binding = "SCENARIOS"
id = "8954bd41bfca46ceaf22712a375382c8"
preview_id = "209b8cf92758482abf04e940f057a0e6"
